In [1]:
from typing import Optional, Tuple, Callable, Union, List
from functools import partial

import jax
import jax.numpy as jnp
from jax import vmap, jit, lax
from jax import random

In [17]:
def multiply(x, time_tree):
    if time_tree is False:
        return x
    else:
        return x * 3

def add(x, add_tree):
    if add_tree is False:
        return x
    else:
        return x + 3

ALL_POTENTIAL_FUNCTIONS = [lambda x: multiply(x, time_tree=True), lambda x: add(x, add_tree=True)]
index = jnp.array([0, 1])
x = jnp.repeat(jnp.array([1]), 2, axis=0)

vmap_function = vmap(lambda i, x: lax.switch(i, ALL_POTENTIAL_FUNCTIONS, x))
vmap_function(index, x)

Array([3, 4], dtype=int32)

In [15]:
def func1(x):
  return 2 * x

def func2(x):
  return -2 * x

def func3(x):
  return 0 * x

functions = [func1, func2, func3]
index = jnp.arange(len(functions))
x = jnp.ones((3, 5))

vmap_functions = vmap(lambda i, x: lax.switch(i, functions, x))
vmap_functions(index, x)

Array([[ 2.,  2.,  2.,  2.,  2.],
       [-2., -2., -2., -2., -2.],
       [ 0.,  0.,  0.,  0.,  0.]], dtype=float32)

In [16]:
index

Array([0, 1, 2], dtype=int32)